# Generated by Django 6.0.3 on 2026-04-27 08:46

import apps.core.models.observation
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.expressions
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='updated at')),
                ('tags', models.JSONField(default=dict, help_text='A dictionary of all tags and their positions. For example: {"LA": "WN(ABC)", "RA": "M"}.', verbose_name='tags')),
                ('search', models.JSONField(default=dict, help_text='A dictionary of key-value pairs which are used to search the tags.', verbose_name='search')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the bird.', verbose_name='comments')),
            ],
            options={
                'verbose_name': 'bird',
                'verbose_name_plural': 'birds',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='updated at')),
                ('name', models.TextField(help_text='The name of the location.', verbose_name='name')),
                ('region', models.CharField(blank=True, help_text='The ISO 3166-2 subdivision code for the region or district where this location is situated.', max_length=6, verbose_name='region')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='The latitude of this location in decimal degrees.', max_digits=8, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='The longitude of this location in decimal degrees.', max_digits=9, null=True, verbose_name='longitude')),
                ('accuracy', models.IntegerField(blank=True, help_text='The estimated distance in metres between the coordinates and the actual position.', null=True, verbose_name='accuracy')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='updated at')),
                ('name', models.TextField(help_text='The name of the project.', verbose_name='name')),
                ('search', models.JSONField(default=dict, help_text='A dictionary of key-value pairs which are used to search for the combinations used by the project.', verbose_name='search')),
                ('description', models.TextField(blank=True, help_text='A description of the project.', verbose_name='description')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('coordinator', models.TextField(help_text='The name of the project coordinator.', verbose_name='coordinator')),
                ('email', models.EmailField(blank=True, help_text='The email address where observations should be sent.', max_length=254, verbose_name='email')),
                ('submit', models.URLField(blank=True, help_text='The URL of a website where observations may be submitted.', verbose_name='submission URL')),
                ('url', models.URLField(blank=True, help_text='The URL of the website describing this project.', verbose_name='website URL')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='updated at')),
                ('order', models.IntegerField(blank=True, help_text='The position in the eBird/Clements taxonomic order.', null=True, verbose_name='taxonomy order')),
                ('code', models.TextField(help_text='The eBird species code used to uniquely identify this species.', unique=True, verbose_name='code')),
                ('common_name', models.JSONField(default=dict, help_text='The standardised common name for the species in each supported language, stored as a JSON object with language codes as keys. For example: {"en": "Mallard", "de": "Stockente", "fr": "colvert"}.', verbose_name='common name')),
                ('scientific_name', models.TextField(help_text='The scientific (Latin) name for the species.', verbose_name='scientific name')),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
            },
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='updated at')),
                ('name', models.TextField(help_text='The full name of the observer.', verbose_name='name')),
                ('user', models.OneToOneField(blank=True, help_text='The user account associated with this observer, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observer', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'observer',
                'verbose_name_plural': 'observers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='updated at')),
                ('event', models.CharField(choices=[('', ''), ('c', 'Capture'), ('r', 'Recapture'), ('o', 'Observation')], default='', help_text='The type of observation: capture, recapture, observation', max_length=1, verbose_name='event')),
                ('tags', models.JSONField(default=dict, help_text='A dictionary of all tags observed and their positions, keyed by position code. For example: {"LA": "WN(ABC)", "RA": "M"}.', verbose_name='tags')),
                ('date', models.DateField(help_text='The date the observation was made.', verbose_name='date')),
                ('time', models.TimeField(blank=True, help_text='The time the observation was made.', null=True, verbose_name='time')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='The precise latitude of the bird, overriding the location coordinates.', max_digits=8, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='The precise longitude of the bird, overriding the location coordinates.', max_digits=9, null=True, verbose_name='longitude')),
                ('photo', models.ImageField(blank=True, help_text='A photo of the bird at the time of observation, used to verify that the tags were read correctly.', upload_to=apps.core.models.observation.photo_path, verbose_name='photo')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the observation.', verbose_name='notes')),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('closed', 'Closed')], default='open', help_text='The progress made in identifying and linking the origin. open: no project identified yet; submitted: project identified and observation submitted to coordinator; closed: origin linked.', max_length=10, verbose_name='status')),
                ('bird', models.ForeignKey(help_text='The colour-ringed observed.', on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.bird', verbose_name='bird')),
                ('location', models.ForeignKey(help_text='The location where the observation was made.', on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.location', verbose_name='location')),
                ('observer', models.ForeignKey(help_text='The person who made this observation.', on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.observer', verbose_name='observer')),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
            },
        ),
        migrations.AddField(
            model_name='bird',
            name='project',
            field=models.ForeignKey(help_text='The project that tagged this bird.', on_delete=django.db.models.deletion.PROTECT, related_name='origins', to='core.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='project',
            name='species',
            field=models.ForeignKey(help_text='The primary species of bird being marked by this project.', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.species', verbose_name='species'),
        ),
        migrations.AddField(
            model_name='bird',
            name='species',
            field=models.ForeignKey(help_text='The species recorded at the time of capture.', on_delete=django.db.models.deletion.PROTECT, related_name='origins', to='core.species', verbose_name='species'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='core_projec_search_56bae4_gin'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(django.db.models.expressions.RawSQL("((search->>'code'))", []), name='idx_project_search_code'),
        ),
        migrations.AddIndex(
            model_name='bird',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='core_bird_search_4fbe95_gin'),
        ),
        migrations.AddIndex(
            model_name='bird',
            index=models.Index(django.db.models.expressions.RawSQL("((search->>'code'))", []), name='idx_bird_search_code'),
        ),
    ]
