# Generated by Django 6.0.3 on 2026-08-30 09:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was the record created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When was the record last updated.', verbose_name='modified')),
                ('code', models.TextField(db_index=True, help_text='The ISO 3166-1 alpha-3 code, or a user-assigned alpha-3 code for a non-ISO entity such as an area at sea.', unique=True, verbose_name='code')),
                ('name', models.TextField(help_text='The name of the country or area.', verbose_name='name')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='The full name of the observer.', verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was the record created.', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When was the record last updated.', verbose_name='updated')),
            ],
            options={
                'verbose_name': 'observer',
                'verbose_name_plural': 'observers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was the record created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When was the record last updated.', verbose_name='updated')),
                ('published', models.DateTimeField(blank=True, help_text='When was the place last updated by Euring.', null=True, verbose_name='published')),
                ('active', models.BooleanField(help_text='Is the Place currently used.', verbose_name='active')),
                ('name', models.JSONField(blank=True, default=dict, help_text='The name of the Place, keyed by script, e.g. {"Latn": "Sofia", "Cyrl": "София"}.', verbose_name='name')),
                ('code', models.TextField(db_index=True, help_text='The Euring Place code for a region.', unique=True, verbose_name='code')),
                ('country', models.ForeignKey(help_text='The country, or other area, for the Place.', on_delete=django.db.models.deletion.PROTECT, related_name='places', to='core.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was the record created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When was the record last updated.', verbose_name='updated')),
                ('name', models.JSONField(blank=True, default=dict, help_text='The name of the Location, keyed by script, e.g. {"Latn": "Sofia", "Cyrl": "София"}.', verbose_name='name')),
                ('label', models.TextField(blank=True, help_text='Label is used to distinguish between sub-sites, which share the name, but have different coordinates.')),
                ('latitude', models.DecimalField(decimal_places=4, help_text='The latitude of this location in decimal degrees.', max_digits=6, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=4, help_text='The longitude of this location in decimal degrees.', max_digits=7, verbose_name='longitude')),
                ('accuracy', models.IntegerField(blank=True, help_text='The estimated distance in metres, from the coordinates, to the actual position of the bird.', null=True, verbose_name='accuracy')),
                ('description', models.TextField(blank=True, help_text='The description of the Location.')),
                ('place', models.ForeignKey(help_text='The region, and country, for the Location.', on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='core.place', verbose_name='place')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was the record created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When was the record last updated.', verbose_name='modified')),
                ('description', models.TextField(blank=True, help_text='A description of the project.', verbose_name='description')),
                ('coordinator', models.TextField(help_text='The name of the project coordinator.', verbose_name='coordinator')),
                ('contact', models.EmailField(blank=True, help_text='The email address where observations should be sent.', max_length=254, verbose_name='contact')),
                ('submit', models.URLField(blank=True, help_text='The website where observations should be submitted.', verbose_name='submit')),
                ('site', models.URLField(blank=True, help_text='The website describing the project.', verbose_name='website')),
                ('country', models.OneToOneField(help_text='The country where the project is based.', on_delete=django.db.models.deletion.PROTECT, related_name='project', to='core.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was the record created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When was the record last updated.', verbose_name='modified')),
                ('age', models.TextField(choices=[('0', 'Age unknown'), ('1', 'Pullus'), ('2', 'Full-grown'), ('3', '1st calendar-year'), ('4', 'After 1st calendar-year'), ('5', '2nd calendar-year'), ('6', 'After 2nd calendar-year'), ('7', '3rd calendar-year'), ('8', 'After 3rd calendar-year'), ('9', '4th calendar-year'), ('A', 'After 4th calendar-year')], default='0', help_text='The age of the bird when it was marked, using the EURING age code.', verbose_name='age')),
                ('sex', models.TextField(choices=[('U', 'Unknown'), ('M', 'Male'), ('F', 'Female')], default='U', help_text='The sex of the bird, using the EURING sex code.', verbose_name='sex')),
                ('date', models.DateField(help_text='The date the bird was marked.', verbose_name='date')),
                ('time', models.TimeField(blank=True, help_text='The time the bird was marked.', null=True, verbose_name='time')),
                ('resolution', models.TextField(choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], default='d', help_text='The units the date is accurate to.', verbose_name='resolution')),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, help_text='The precise latitude of the bird, overriding the location coordinates.', max_digits=6, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, help_text='The precise longitude of the bird, overriding the location coordinates.', max_digits=7, null=True, verbose_name='longitude')),
                ('accuracy', models.IntegerField(blank=True, help_text='The estimated distance in metres, from the coordinates, to the actual position of the bird.', null=True, verbose_name='accuracy')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the bird.', verbose_name='comments')),
                ('location', models.ForeignKey(help_text='The location where the bird was marked.', on_delete=django.db.models.deletion.PROTECT, related_name='captures', to='core.location', verbose_name='location')),
                ('project', models.ForeignKey(help_text='The project that tagged this bird.', on_delete=django.db.models.deletion.PROTECT, related_name='captures', to='core.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'capture',
                'verbose_name_plural': 'captures',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was the record created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When was the record last updated.', verbose_name='modified')),
                ('code', models.TextField(help_text='The 5-digit EURING code used to uniquely identify this species.', unique=True, validators=[django.core.validators.RegexValidator(message="The code must be the 5-digit EURING species code, e.g. '00020'.", regex='^\\d{5}$')], verbose_name='code')),
                ('scientific_name', models.TextField(help_text='The scientific (Latin) name for the species.', verbose_name='scientific name')),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^\\d{5}$')), name='species_code_is_5_digit_euring_code')],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was the record created.', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When was the record last updated.', verbose_name='updated')),
                ('position', models.TextField(choices=[('LA', 'Left Above (tibia)'), ('LB', 'Left Below (tarsus)'), ('LW', 'Left Wing'), ('S', 'Nasal Saddle'), ('C', 'Neck Collar'), ('RA', 'Right Above (tibia)'), ('RB', 'Right Below (tarsus)'), ('RW', 'Right Wing')], help_text='The position of the colour mark on the bird.', verbose_name='position')),
                ('regex', models.TextField(help_text='A regular expression for matching colour marks.', verbose_name='regex')),
                ('project', models.ForeignKey(help_text='The project that marked the bird.', on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='core.project', verbose_name='project')),
                ('species', models.ForeignKey(help_text='The species of bird being marked by the project.', on_delete=django.db.models.deletion.PROTECT, related_name='patterns', to='core.species', verbose_name='species')),
            ],
            options={
                'verbose_name': 'rule',
                'verbose_name_plural': 'rules',
            },
        ),
        migrations.CreateModel(
            name='Resighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was the record created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When was the record last updated.', verbose_name='modified')),
                ('submitted', models.DateTimeField(blank=True, help_text='When was the record submitted to the project coordinator.', null=True, verbose_name='submitted')),
                ('date', models.DateField(help_text='The date the resighting was made.', verbose_name='date')),
                ('time', models.TimeField(blank=True, help_text='The time the resighting was made.', null=True, verbose_name='time')),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, help_text='The precise latitude of the bird, overriding the location coordinates.', max_digits=6, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, help_text='The precise longitude of the bird, overriding the location coordinates.', max_digits=7, null=True, verbose_name='longitude')),
                ('accuracy', models.IntegerField(blank=True, help_text='The estimated distance in metres, from the coordinates, to the actual position of the bird.', null=True, verbose_name='accuracy')),
                ('photo', models.ImageField(blank=True, help_text='A photo of the bird at the time of the resighting. Used to verify that the tags were read correctly.', upload_to='resightings/%Y/%m/%d/', verbose_name='photo')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the resighting.', verbose_name='notes')),
                ('capture', models.ForeignKey(blank=True, help_text='The details of where the bird was marked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resightings', to='core.capture', verbose_name='capture')),
                ('location', models.ForeignKey(help_text='The location where the resighting was made.', on_delete=django.db.models.deletion.PROTECT, related_name='resightings', to='core.location', verbose_name='location')),
                ('observer', models.ForeignKey(help_text='The person who made this resighting.', on_delete=django.db.models.deletion.PROTECT, related_name='resightings', to='core.observer', verbose_name='observer')),
                ('species', models.ForeignKey(help_text='The species observed.', on_delete=django.db.models.deletion.PROTECT, related_name='resightings', to='core.species', verbose_name='species')),
            ],
            options={
                'verbose_name': 'resighting',
                'verbose_name_plural': 'resightings',
            },
        ),
        migrations.AddField(
            model_name='capture',
            name='species',
            field=models.ForeignKey(help_text='The species recorded at the time of capture.', on_delete=django.db.models.deletion.PROTECT, related_name='captures', to='core.species', verbose_name='species'),
        ),
        migrations.CreateModel(
            name='SpeciesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text="The ISO 639-1 language code for this name, e.g. 'en' or 'pt-br'.", max_length=7, verbose_name='language')),
                ('common_name', models.TextField(help_text='The common name for the species in this language.', verbose_name='common name')),
                ('species', models.ForeignKey(help_text='The species this name belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='names', to='core.species', verbose_name='species')),
            ],
            options={
                'verbose_name': 'species name',
                'verbose_name_plural': 'species names',
                'constraints': [models.UniqueConstraint(fields=('species', 'language_code'), name='unique_species_language')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was the record created.', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When was the record last updated.', verbose_name='updated')),
                ('position', models.TextField(choices=[('LA', 'Left Above (tibia)'), ('LB', 'Left Below (tarsus)'), ('LW', 'Left Wing'), ('S', 'Nasal Saddle'), ('C', 'Neck Collar'), ('RA', 'Right Above (tibia)'), ('RB', 'Right Below (tarsus)'), ('RW', 'Right Wing')], help_text='The position of the tag on the bird.', verbose_name='position')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Stacking order (top to bottom) among tags sharing the same position.', verbose_name='order')),
                ('kind', models.TextField(choices=[('R', 'Ring'), ('F', 'Flag'), ('S', 'Nasal saddle'), ('W', 'Wing tag'), ('C', 'Neck collar')], default='R', help_text='The physical type of tag.', verbose_name='kind')),
                ('colour', models.TextField(choices=[('R', 'Red'), ('P', 'Light Blue'), ('W', 'White'), ('O', 'Orange'), ('G', 'Dark Green'), ('C', 'Dark Pink (Carmine)'), ('L', 'Light Green (Lime)'), ('K', 'Light Pink'), ('N', 'Black (Niger)'), ('B', 'Dark Blue'), ('M', 'Metal Ring'), ('V', 'Violet/Mauve/Purple'), ('Y', 'Yellow'), ('S', 'Silver/Grey'), ('A', 'Other metal ring'), ('U', 'Brown (Umber)'), ('Q', 'Turquoise')], help_text='The colour of the tag.', verbose_name='colour')),
                ('second_colour', models.TextField(blank=True, choices=[('R', 'Red'), ('P', 'Light Blue'), ('W', 'White'), ('O', 'Orange'), ('G', 'Dark Green'), ('C', 'Dark Pink (Carmine)'), ('L', 'Light Green (Lime)'), ('K', 'Light Pink'), ('N', 'Black (Niger)'), ('B', 'Dark Blue'), ('M', 'Metal Ring'), ('V', 'Violet/Mauve/Purple'), ('Y', 'Yellow'), ('S', 'Silver/Grey'), ('A', 'Other metal ring'), ('U', 'Brown (Umber)'), ('Q', 'Turquoise')], help_text='The second colour, for a two-colour striped ring.', verbose_name='second colour')),
                ('inscription', models.TextField(blank=True, help_text='The engraved text on the tag, if any.', verbose_name='inscription')),
                ('inscription_colour', models.TextField(blank=True, choices=[('R', 'Red'), ('P', 'Light Blue'), ('W', 'White'), ('O', 'Orange'), ('G', 'Dark Green'), ('C', 'Dark Pink (Carmine)'), ('L', 'Light Green (Lime)'), ('K', 'Light Pink'), ('N', 'Black (Niger)'), ('B', 'Dark Blue'), ('M', 'Metal Ring'), ('V', 'Violet/Mauve/Purple'), ('Y', 'Yellow'), ('S', 'Silver/Grey'), ('A', 'Other metal ring'), ('U', 'Brown (Umber)'), ('Q', 'Turquoise')], help_text='The colour of the inscription, if different from the tag itself.', verbose_name='inscription colour')),
                ('inscription_direction', models.TextField(blank=True, choices=[('D', 'Downward'), ('H', 'Horizontal'), ('U', 'Upward')], help_text='The direction the inscription reads in, if it could be ambiguous.', verbose_name='inscription direction')),
                ('uncertain', models.BooleanField(default=False, help_text='Was some part of this tag not clearly seen or read?', verbose_name='uncertain')),
                ('capture', models.ForeignKey(blank=True, help_text='The Capture that the tag belongs to, if attached when the bird was marked.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.capture', verbose_name='capture')),
                ('resighting', models.ForeignKey(blank=True, help_text='The Resighting that the tag belongs to, if read on a later sighting.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.resighting', verbose_name='resighting')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['position', 'order'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('capture__isnull', False), ('resighting__isnull', True)), models.Q(('capture__isnull', True), ('resighting__isnull', False)), _connector='OR'), name='tag_belongs_to_exactly_one_owner')],
            },
        ),
    ]
