# Generated by Django 6.0.3 on 2026-08-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='observer',
            field=models.OneToOneField(blank=True, help_text='The observer associated with this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.observer', verbose_name='observer'),
        ),
    ]
